spring:
  application:
    name: rag-ai-chatbot
  ai:
    openai:
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: mistralai/mistral-7b-instruct:free
    transformers:
      embedding:
        enabled: true
        model: "BAAI/bge-small-en"

    vectorstore:
      pgvector:
        enabled: true
        table-name: vector_store
        indexType: "IVFFlat"
        lists: 100
        distance-type: "COSINE_DISTANCE"

  datasource:
    enabled: true

logging:
  level:
    root: WARN
    ch.bzz.rag: DEBUG
    ch.bzz.rag.service: DEBUG
  file:
    name: app.log
